### ISSUE TITLE
Viki ERROR: name 'mpd_url' is not defined

### ISSUE THREAD

**Issue by fursiol0800** [zackmark29/yt-dlp#2]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
lucas@DESKTOP-5PGNH3H:~/viki/yt-dlp-2021-07-09$ ./yt-dlp.sh -i "https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3" --write-sub --sub-lang en --sub-format vtt --verbose
[debug] Command-line config: ['-i', 'https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3', '--write-sub', '--sub-lang', 'en', '--sub-format', 'vtt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.06.23 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3
[viki] 1183563v: Downloading video JSON
[viki] 1183563v: Downloading video streams JSON
[viki] 1183563v: Checking for another mpd url
ERROR: name 'mpd_url' is not defined
Traceback (most recent call last):
  File "/home/lucas/viki/yt-dlp-2021.07.08/viki/yt-dlp-2021-07-09/yt_dlp/YoutubeDL.py", line 1144, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lucas/viki/yt-dlp-2021.07.08/viki/yt-dlp-2021-07-09/yt_dlp/YoutubeDL.py", line 1169, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lucas/viki/yt-dlp-2021.07.08/viki/yt-dlp-2021-07-09/yt_dlp/extractor/common.py", line 569, in extract
    ie_result = self._real_extract(url)
  File "/home/lucas/viki/yt-dlp-2021.07.08/viki/yt-dlp-2021-07-09/yt_dlp/extractor/viki.py", line 307, in _real_extract
    formats = self._extract_mpd_formats(mpd_url, video_id)
NameError: name 'mpd_url' is not defined

```

## Description

WRITE DESCRIPTION HERE
all videos give this error: name 'mpd_url' is not defined

**Comment by zackmark29** [comment]
You use the old version. 
Use this latest 
https://github.com/zackmark29/yt-dlp/releases/tag/2021-07-09

**Comment by zackmark29** [comment]
Ah you're using linux. Try now the updated codes

**Comment by fursiol0800** [comment]
Maybe i am doing something wrong but i still get the same error:


```
lucas@DESKTOP-5PGNH3H:~/viki/yt-dlp-2021-07-09$ uname -a
Linux DESKTOP-5PGNH3H 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux


lucas@DESKTOP-5PGNH3H:~/viki$ wget "https://github.com/zackmark29/yt-dlp/archive/refs/tags/2021-07-09.zip"
lucas@DESKTOP-5PGNH3H:~/viki$ unzip 2021-07-09.zip
lucas@DESKTOP-5PGNH3H:~/viki$ cd yt-dlp-2021-07-09/


lucas@DESKTOP-5PGNH3H:~/viki/yt-dlp-2021-07-09$ ./yt-dlp.sh "https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3" --verbose
[debug] Command-line config: ['https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.06.23 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3
[viki] 1183563v: Downloading video JSON
[viki] 1183563v: Downloading video streams JSON
[viki] 1183563v: Checking for another mpd url
ERROR: name 'mpd_url' is not defined
Traceback (most recent call last):
  File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/YoutubeDL.py", line 1144, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/YoutubeDL.py", line 1169, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/extractor/common.py", line 569, in extract
    ie_result = self._real_extract(url)
  File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/extractor/viki.py", line 307, in _real_extract
    formats = self._extract_mpd_formats(mpd_url, video_id)
NameError: name 'mpd_url' is not defined
```

**Comment by zackmark29** [comment]
> Maybe i am doing something wrong but i still get the same error:
> 
> ```
> lucas@DESKTOP-5PGNH3H:~/viki/yt-dlp-2021-07-09$ uname -a
> Linux DESKTOP-5PGNH3H 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
> 
> 
> lucas@DESKTOP-5PGNH3H:~/viki$ wget "https://github.com/zackmark29/yt-dlp/archive/refs/tags/2021-07-09.zip"
> lucas@DESKTOP-5PGNH3H:~/viki$ unzip 2021-07-09.zip
> lucas@DESKTOP-5PGNH3H:~/viki$ cd yt-dlp-2021-07-09/
> 
> 
> lucas@DESKTOP-5PGNH3H:~/viki/yt-dlp-2021-07-09$ ./yt-dlp.sh "https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3" --verbose
> [debug] Command-line config: ['https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3', '--verbose']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] yt-dlp version 2021.06.23 (source)
> [debug] Plugin Extractors: ['SamplePlugin']
> [debug] Python version 3.6.9 (CPython 64bit) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-18.04-bionic
> [debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
> [debug] Proxy map: {}
> [debug] [viki] Extracting URL: https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3
> [viki] 1183563v: Downloading video JSON
> [viki] 1183563v: Downloading video streams JSON
> [viki] 1183563v: Checking for another mpd url
> ERROR: name 'mpd_url' is not defined
> Traceback (most recent call last):
>   File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/YoutubeDL.py", line 1144, in wrapper
>     return func(self, *args, **kwargs)
>   File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/YoutubeDL.py", line 1169, in __extract_info
>     ie_result = ie.extract(url)
>   File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/extractor/common.py", line 569, in extract
>     ie_result = self._real_extract(url)
>   File "/home/lucas/viki/yt-dlp-2021-07-09/yt_dlp/extractor/viki.py", line 307, in _real_extract
>     formats = self._extract_mpd_formats(mpd_url, video_id)
> NameError: name 'mpd_url' is not defined
> ```

You should download the latest binary, I have updated only the version from 2021-07-09
