### ISSUE TITLE
Viki : Cannot download premium episodes with cookies file

### ISSUE THREAD

**Issue by TiTnOuK** [zackmark29/yt-dlp#3]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ yt-dlp -F  "https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3" --cookies "cookies_viki.txt" --verbose
[debug] Command-line config: ['-F', 'https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '--cookies', 'cookies_viki.txt', '--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] yt-dlp version 2021.07.07 (zip)
[debug] Python version 3.6.10 (CPython 64bit) - Linux-5.10.25-linuxkit-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3
[viki] 1181208v: Downloading video JSON
ERROR: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1167, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 569, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/viki.py", line 252, in _real_extract
    self._check_errors(video)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/viki.py", line 99, in _check_errors
    self.raise_login_required(message)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1043, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials

```

## Description

I have a premium account on Viki and when I use my exported cookies file to download episodes (seems to be start with 3rd episode for series which needed premium access) I have an error.

I use [this extension](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) to extract my cookies

**Comment by zackmark29** [comment]
You don't need to export cookies. Just pass the username and password

**Comment by zackmark29** [comment]
```

[debug] Command-line config: ['https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', '0', '-v', '--skip-download', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: dc34f1943
[debug] Python version 3.6.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-102009-gefdb564504
[debug] Proxy map: {}
[viki] Logging in
[debug] [viki] Extracting URL: https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3
[viki] 1181208v: Downloading video JSON
[viki] 1181208v: Downloading video streams JSON
[viki] 1181208v: Downloading initial MPD manifest
[viki] 1181208v: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1181208v:
ID    EXT   RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
----- ----- ---------- --- - ----- ----- - ----------- ----- --------- ---- ------- ------------------------------------
image mhtml images         |       mhtml |                                          DASH storyboards (jpeg)
6     m4a   audio only     |   49k https |                   mp4a.40.2  49k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
7     m4a   audio only     |   65k https |                   mp4a.40.2  65k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
5     m4a   audio only     |   81k https |                   mp4a.40.2  81k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
8     m4a   audio only     |  193k https |                   mp4a.40.2 193k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
9     m4a   audio only     |  193k https |                   mp4a.40.2 193k 48000Hz [eng], DASH audio, m4a_dash, 48000Hz
1     mp4   426x238    24  |  170k https | avc1.640015  170k                        DASH video, mp4_dash
2     mp4   640x360    24  |  324k https | avc1.64001E  324k                        DASH video, mp4_dash
3     mp4   852x480    24  |  500k https | avc1.64001E  500k                        DASH video, mp4_dash
4     mp4   1280x720   24  |  965k https | avc1.64001F  965k                        DASH video, mp4_dash
0     mp4   1920x1080  24  | 2185k https | avc1.640028 2185k                        DASH video, mp4_dash
```

**Comment by TiTnOuK** [comment]
Ok, unfortunately even using my credentials, it does not work :(

```
[debug] Command-line config: ['https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', '0', '-v', '--skip-download', '-F']
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] yt-dlp version 2021.07.07 (zip)
[debug] Python version 3.6.10 (CPython 64bit) - Linux-5.10.25-linuxkit-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0
[debug] Proxy map: {}
[viki] Logging in
WARNING: [viki] Unable to download JSON metadata: HTTP Error 404: Not Found
WARNING: [viki] Login Failed: Unable to get session token
[debug] [viki] Extracting URL: https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3
[viki] 1181208v: Downloading video JSON
ERROR: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1167, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 569, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/viki.py", line 252, in _real_extract
    self._check_errors(video)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/viki.py", line 99, in _check_errors
    self.raise_login_required(message)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1043, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
```

**Comment by zackmark29** [comment]
> Ok, unfortunately even using my credentials, it does not work :(
> 
> ```
> [debug] Command-line config: ['https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', '0', '-v', '--skip-download', '-F']
> [debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
> [debug] yt-dlp version 2021.07.07 (zip)
> [debug] Python version 3.6.10 (CPython 64bit) - Linux-5.10.25-linuxkit-x86_64-with-debian-9.13
> [debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0
> [debug] Proxy map: {}
> [viki] Logging in
> WARNING: [viki] Unable to download JSON metadata: HTTP Error 404: Not Found
> WARNING: [viki] Login Failed: Unable to get session token
> [debug] [viki] Extracting URL: https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3
> [viki] 1181208v: Downloading video JSON
> ERROR: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
> Traceback (most recent call last):
>   File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1142, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1167, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 569, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/viki.py", line 252, in _real_extract
>     self._check_errors(video)
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/viki.py", line 99, in _check_errors
>     self.raise_login_required(message)
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1043, in raise_login_required
>     raise ExtractorError(msg, expected=True)
> yt_dlp.utils.ExtractorError: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
> ```

Ahm. what is your viki plan type?

**Comment by zackmark29** [comment]
```
WARNING: [viki] Login Failed: Unable to get session token
```
Looks like it's account problem. or tell me your viki subscription plan
I'll take a look tomorrow

**Comment by TiTnOuK** [comment]
My plan was Viki Pass Standard during my previous test because Viki Pass Plus is not available for my country (France).
So I tried like you with a VPN (connected to US) and I subscribe to Viki Pass Plus but same result.

**Comment by zackmark29** [comment]
> My plan was Viki Pass Standard during my previous test because Viki Pass Plus is not available for my country (France).
> So I tried like you with a VPN (connected to US) and I subscribed to Viki Pass Plus but it doesn't work either.
> 
> ```
> [debug] Command-line config: ['https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', '0', '-v', '--skip-download', '-F']
> [debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
> [debug] yt-dlp version 2021.07.07 (zip)
> [debug] Python version 3.6.10 (CPython 64bit) - Linux-5.10.25-linuxkit-x86_64-with-debian-9.13
> [debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0
> [debug] Proxy map: {}
> [viki] Logging in
> ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3086, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> ```

Ahm I tried again with vpn connected to France. And didn't get any error as well.
Can you add this command so we can see the response data
--write-pages

**Comment by zackmark29** [comment]
And I also see you're using old version.
This is the latest
https://github.com/zackmark29/yt-dlp/releases/tag/2021-07-09

**Comment by TiTnOuK** [comment]
I have this error on Unix based system (Linux or MacOS) executed with yt-dlp.sh (with or without VPN)
I have only one dump file with `--write-pages`
[1181208v_https_-_api.viki.io_v4_videos_1181208v.jsonapp=100005a.txt](https://github.com/zackmark29/yt-dlp/files/6795997/1181208v_https_-_api.viki.io_v4_videos_1181208v.jsonapp.100005a.txt)

```
[debug] Command-line config: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '-f', '0', '-v', '--skip-download', '-F', '--write-pages']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: dc34f1943
[debug] Python version 3.9.2 (CPython 64bit) - macOS-11.4-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[viki] Logging in
WARNING: [viki] Unable to download JSON metadata: HTTP Error 404: Not Found
WARNING: [viki] Login Failed: Unable to get session token
[debug] [viki] Extracting URL: https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3
[viki] 1181208v: Downloading video JSON
ERROR: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/Users/titnouk/Dev/docker/anicapt/yt/yt-dlp/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/titnouk/Dev/docker/anicapt/yt/yt-dlp/yt_dlp/YoutubeDL.py", line 1167, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/titnouk/Dev/docker/anicapt/yt/yt-dlp/yt_dlp/extractor/common.py", line 569, in extract
    ie_result = self._real_extract(url)
  File "/Users/titnouk/Dev/docker/anicapt/yt/yt-dlp/yt_dlp/extractor/viki.py", line 252, in _real_extract
    self._check_errors(video)
  File "/Users/titnouk/Dev/docker/anicapt/yt/yt-dlp/yt_dlp/extractor/viki.py", line 99, in _check_errors
    self.raise_login_required(message)
  File "/Users/titnouk/Dev/docker/anicapt/yt/yt-dlp/yt_dlp/extractor/common.py", line 1043, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
```

But I tried with .exe binary on a Windows and it's seems to work.

**Comment by zackmark29** [comment]
> I have this error on Unix based system (Linux or MacOS) executed with yt-dlp.sh (with or without VPN)
> I have only one dump file with `--write-pages`
> [1181208v_https_-_api.viki.io_v4_videos_1181208v.jsonapp=100005a.txt](https://github.com/zackmark29/yt-dlp/files/6795997/1181208v_https_-_api.viki.io_v4_videos_1181208v.jsonapp.100005a.txt)
> 
> Proof that I have a Viki Pass Plus : https://imgur.com/a/taSOvaU
> 
> ```
> [debug] Command-line config: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3', '-f', '0', '-v', '--skip-download', '-F', '--write-pages']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] yt-dlp version 2021.07.07 (source)
> [debug] Plugin Extractors: ['SamplePlugin']
> [debug] Git HEAD: dc34f1943
> [debug] Python version 3.9.2 (CPython 64bit) - macOS-11.4-x86_64-i386-64bit
> [debug] exe versions: rtmpdump 2.4
> [debug] Proxy map: {}
> [viki] Logging in
> WARNING: [viki] Unable to download JSON metadata: HTTP Error 404: Not Found
> WARNING: [viki] Login Failed: Unable to get session token
> [debug] [viki] Extracting URL: https://www.viki.com/videos/1181208v-so-i-married-the-anti-fan-episode-3
> [viki] 1181208v: Downloading video JSON
> ERROR: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
> Traceback (most recent call last):
>   File "/home/yt-dlp/yt_dlp/YoutubeDL.py", line 1142, in wrapper
>     return func(self, *args, **kwargs)
>   File "/home/yt-dlp/yt_dlp/YoutubeDL.py", line 1167, in __extract_info
>     ie_result = ie.extract(url)
>   File "/home/yt-dlp/yt_dlp/extractor/common.py", line 569, in extract
>     ie_result = self._real_extract(url)
>   File "/home/yt-dlp/yt_dlp/extractor/viki.py", line 252, in _real_extract
>     self._check_errors(video)
>   File "/home/yt-dlp/yt_dlp/extractor/viki.py", line 99, in _check_errors
>     self.raise_login_required(message)
>   File "/home/yt-dlp/yt_dlp/extractor/common.py", line 1043, in raise_login_required
>     raise ExtractorError(msg, expected=True)
> yt_dlp.utils.ExtractorError: Sorry, this content is only available to Viki Pass Plus subscribers. Use --cookies, --username and --password or --netrc to provide account credentials
> ```
> 
> But I tried with .exe binary on a Windows and it's seems to work.

Yes exe should work. I don't know how to fix with other operating system. Just wait for linux build you can check from original dlp source
